apiVersion: batch/v1
kind: Job
metadata:
  name: init
spec:
  template:
    spec:
      containers:
      - name: init
        image: acronboarding.azurecr.io/acronboarding.azurecr.io:216
        env:
          - name: MONGODB_CONNECTION
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: db
      restartPolicy: Never
  backoffLimit: 4